AWSTemplateFormatVersion: '2010-09-09'
Description: Code pipeline
Parameters:
  PipelineName:
    Type: String
  MainStackName:
    Type: String
  Role:
    Type: String
  CodeRepo:
    Type: String
  ProjectName:
    Type: String
  Branch:
    Type: String
  GitHubOAuthToken:
    Type: String
  Env:
    Type: String
  ArtifactBucket:
    Type: String
  S3TempBucket:
    Type: String
Resources:

  CFNExecutionRole:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3-${AWS::Region}.amazonaws.com/${S3TempBucket}/iam-cfn-role.yml
      Parameters:
        ProjectName: !Ref ProjectName
        Env: !Ref Env
  
  CodeBuildLambda:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3-${AWS::Region}.amazonaws.com/${S3TempBucket}/codebuild-lambda-build.yml
      Parameters:
        ProjectName: !Ref ProjectName
        Role: !Ref Role
        ArtifactBucket: !Ref ArtifactBucket
        BuildSpecFile: "buildspec.yml"
        Env: !Ref Env

  CodeBuildLint:
    Type: AWS::CloudFormation::Stack
    Condition: CreateBuildResources
    Properties:
      TemplateURL: !Sub https://s3-${AWS::Region}.amazonaws.com/${S3TempBucket}/codebuild-project.yml
      Parameters:
        BuildStep: "lint"
        BuildSpecFile: "buildspec-lint.yml"
        Role: !Ref Role
        ProjectName: !Ref ProjectName
        Env: !Ref Env
  
  CodeBuildTest:
    Type: AWS::CloudFormation::Stack
    Condition: CreateBuildResources
    Properties:
      TemplateURL: !Sub https://s3-${AWS::Region}.amazonaws.com/${S3TempBucket}/codebuild-project.yml
      Parameters:
        BuildStep: "lint"
        BuildSpecFile: "buildspec-test.yml"
        Role: !Ref Role
        ProjectName: !Ref ProjectName
        Env: !Ref Env
  
  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Ref PipelineName
      ArtifactStore:
        Type: S3
        Location: !Ref ArtifactsBucket
      RoleArn: !Ref Role
      Stages:

      # Source stage

      - Name: Source
        Actions:
        - InputArtifacts: []
          Name: Source
          ActionTypeId:
            Category: Source
            Owner: ThirdParty
            Version: '1'
            Provider: GitHub
          OutputArtifacts:
          - Name: source-out
          Configuration:
            Owner: jorgehdzg1991
            Repo: !Ref CodeRepo
            Branch: !Ref Branch
            OAuthToken: !Ref GitHubOAuthToken
          RunOrder: 1
      
      # Build stage

      - Name: Build
        Actions:

        - Name: LambdaBuild
          InputArtifacts:
          - Name: source-out
          ActionTypeId:
            Category: Build
            Owner: AWS
            Version: '1'
            Provider: CodeBuild
          OutputArtifacts:
          - Name: build-out
          Configuration:
            ProjectName: !GetAtt CodeBuildLambda.Outputs.BuildConfig
          RunOrder: 1
      
        - Name: Lint
          InputArtifacts:
          - Name: source-out
          ActionTypeId:
            Category: Build
            Owner: AWS
            Version: '1'
            Provider: CodeBuild
          OutputArtifacts:
          - Name: lint-out
          Configuration:
            ProjectName: !GetAtt CodeBuildLint.Outputs.BuildConfig
          RunOrder: 1
        
        - Name: Test
          InputArtifacts:
          - Name: source-out
          ActionTypeId:
            Category: Build
            Owner: AWS
            Version: '1'
            Provider: CodeBuild
          OutputArtifacts:
          - Name: test-out
          Configuration:
            ProjectName: !GetAtt CodeBuildTest.Outputs.BuildConfig
          RunOrder: 1
      
