AWSTemplateFormatVersion: '2010-09-09'
Description: Lint/Test/Docs build
Parameters:
  BuildStep:
    Type: String
  BuildSpecFile:
    Type: String
  Role:
    Type: String
  ProjectName:
    Type: String
  Env:
    Type: String
Resources:
  BuildConfig:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub ${ProjectName}-codebuild-${BuildStep}-${Env}
      ServiceRole: !Ref Role
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/nodejs:8.11.0
        Type: LINUX_CONTAINER
      Source:
        BuildSpec: !Ref BuildSpecFile
        Type: CODEPIPELINE
Outputs:
  BuildConfig:
    Description: Build configuration
    Value: !Ref BuildConfig
