AWSTemplateFormatVersion: '2010-09-09'
Description: Pipeline cloud formation role
Parameters:
  ProjectName:
    Type: String
  Env:
    Type: String
Resources:
  CloudFormationExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${ProjectName}-${Env}-cfn
      Path: "/"
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - cloudformation.amazonaws.com
          Action:
          - sts:AssumeRole
      Policies:
        - PolicyName: root
          PolicyDocument: {
            "Statement": [
              {
                "Effect": "Allow",
                "Action": "*",
                "Resource": "*"
              }
            ]
          }
Outputs:
  Role:
    Description: ARN of the Role
    Value: !GetAtt CloudFormationExecutionRole.Arn